# Generated by Django 3.2.8 on 2022-02-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fitnessplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
