# Generated by Django 3.2.8 on 2022-03-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20220220_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessplan',
            name='image',
            field=models.ImageField(default=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
