# Generated by Django 4.0.3 on 2022-04-03 10:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_beauty_culture_food_health_love'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('summary', models.TextField(default='')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('premium', models.BooleanField(default=True)),
            ],
        ),
    ]
