# Generated by Django 4.0.3 on 2022-04-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_beauty_text_culture_text_health_text_love_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fitness',
            new_name='FitnessBlog',
        ),
    ]
